### PR TITLE
width of footer managed in each page, front page more formal.(this pull request is for Hacktoberfest)

### PR DESCRIPTION
**Pull request by nishu91020**

### CODE REVIEW

**Comment by Castella1313** [comment]
did you check out the website after the changes you have made??

**Comment by Castella1313** [comment]
as you have moved the files in new folders, the location of the images and js files is changed, they aren't working

**Comment by Castella1313** [comment]
you must fix them up!!

**Comment by nishu91020** [comment]
I have changed the path as well but I will check it again if that is the case.

**Comment by nishu91020** [comment]
<head>
  <meta charset="UTF-8">	  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="styles.css" />	  <link rel="stylesheet" href="./css/styles.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />	  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
  <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>	  <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
  <title>Hacktober Fest</title>	  <title>Hacktober Fest</title>
</head>	</head>


<body>	<body>
  <header id="header">	


    	    


@@ -39,9 +39,11 @@ <h3>Hacktober Fest</h3>
      </ul>	      </ul>
    </nav>	    </nav>


    <header id="header">
    	    


    <section id="banner">	    <section id="banner">
      
      <div id="banner-box">	      <div id="banner-box">
        <div>	        <div>
          <br />	          <br />
@@ -69,7 +71,7 @@ <h1 id="banner-title">Hacktober Fest 2020</h1>
        <h3 class="banner-subtitle">	        <h3 class="banner-subtitle">
          DSC JIIT - 128 brings you the most famous event for beginners to get started with Open Source	          DSC JIIT - 128 brings you the most famous event for beginners to get started with Open Source
        </h3>	        </h3>
        <a class="banner-btn" href="/about.html">Explore</i></a>	        <a class="banner-btn" href="index.html">Explore</i></a>
      </div>	      </div>
    </section>	    </section>
  </header>	  </header>
@@ -183,16 +185,16 @@ <h2>
    <h4 class="contact-text">CONTACT US</h4>	    <h4 class="contact-text">CONTACT US</h4>
    <h4 class="contact-text">© 2020 DigitalOcean, LLC. All rights reserved</h4>	    <h4 class="contact-text">© 2020 DigitalOcean, LLC. All rights reserved</h4>
    <div class="contact">	    <div class="contact">
      <a href="https://www.facebook.com/dscjiitnoida/"></a>	      <a href="https://www.facebook.com/dscjiitnoida/"></a>
      <a href="https://github.com/dsc-jiit-128"></a></a>	      <a href="https://github.com/dsc-jiit-128"></a></a>
      <a href="mailto:dscjiit128@gmail.com"></a></a>	      <a href="mailto:dscjiit128@gmail.com"></a></a>
      <a href="https://www.instagram.com/dscj128/?hl=en"></a></a>	      <a href="https://www.instagram.com/dscj128/?hl=en"></a></a>
      <a href="https://twitter.com/Dsc128"></a>	      <a href="https://twitter.com/Dsc128"></a>
    </div>	    </div>
  </footer>	  </footer>


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="index.js"></script>	  <script src="./js/index.js"></script>
</body>	</body>


</html>	</html>

**Comment by nishu91020** [comment]
@Castella1313 everything is fine on my side, I have changed all the paths please check.
`<head>
  <meta charset="UTF-8">	  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="styles.css" />	  <link rel="stylesheet" href="./css/styles.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />	  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
  <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>	  <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
  <title>Hacktober Fest</title>	  <title>Hacktober Fest</title>
</head>	</head>


<body>	<body>
  <header id="header">	


    	    


@@ -39,9 +39,11 @@ <h3>Hacktober Fest</h3>
      </ul>	      </ul>
    </nav>	    </nav>


    <header id="header">
    	    


    <section id="banner">	    <section id="banner">
      
      <div id="banner-box">	      <div id="banner-box">
        <div>	        <div>
          <br />	          <br />
@@ -69,7 +71,7 @@ <h1 id="banner-title">Hacktober Fest 2020</h1>
        <h3 class="banner-subtitle">	        <h3 class="banner-subtitle">
          DSC JIIT - 128 brings you the most famous event for beginners to get started with Open Source	          DSC JIIT - 128 brings you the most famous event for beginners to get started with Open Source
        </h3>	        </h3>
        <a class="banner-btn" href="/about.html">Explore</i></a>	        <a class="banner-btn" href="index.html">Explore</i></a>
      </div>	      </div>
    </section>	    </section>
  </header>	  </header>
@@ -183,16 +185,16 @@ <h2>
    <h4 class="contact-text">CONTACT US</h4>	    <h4 class="contact-text">CONTACT US</h4>
    <h4 class="contact-text">© 2020 DigitalOcean, LLC. All rights reserved</h4>	    <h4 class="contact-text">© 2020 DigitalOcean, LLC. All rights reserved</h4>
    <div class="contact">	    <div class="contact">
      <a href="https://www.facebook.com/dscjiitnoida/"></a>	      <a href="https://www.facebook.com/dscjiitnoida/"></a>
      <a href="https://github.com/dsc-jiit-128"></a></a>	      <a href="https://github.com/dsc-jiit-128"></a></a>
      <a href="mailto:dscjiit128@gmail.com"></a></a>	      <a href="mailto:dscjiit128@gmail.com"></a></a>
      <a href="https://www.instagram.com/dscj128/?hl=en"></a></a>	      <a href="https://www.instagram.com/dscj128/?hl=en"></a></a>
      <a href="https://twitter.com/Dsc128"></a>	      <a href="https://twitter.com/Dsc128"></a>
    </div>	    </div>
  </footer>	  </footer>


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="index.js"></script>	  <script src="./js/index.js"></script>
</body>	</body>


</html>	</html>`

**Review by ads-22 — CHANGES_REQUESTED** [review]
Just make The github icon in the footer visible.

**Comment by nishu91020** [comment]
ok, I will change the color so that it is visible:)

**Comment by nishu91020** [comment]
@ads-22 kindly check it out.

**Pull request merged**
