### PR TITLE
 Added footer faq page and fixed css & fixed logo typo errors with links 

### PR DESCRIPTION
**Pull request by pranav2012**
#11  #19

### CODE REVIEW

**Comment by pranav2012** [comment]
please review and merge

**Comment by pranav2012** [comment]
please review and merge

**Comment by pranav2012** [comment]
hey, @Castella1313 Please review and merge

**Comment by Castella1313** [comment]
@pranav2012 nice work :)

**Comment by pranav2012** [comment]
Thanks alot for the guidance @Castella1313 😊

**Comment by pranav2012** [comment]
Hey @Castella1313 can you please add a hacktober-accepted label to this pull request according to the new rules only such pull requests are validd . Thank you

**Comment by pranav2012** [comment]
## hacktoberfest new rule point 3
image
Thanks, @Castella1313 please change the label name to "hacktoberfest-accepted" sorry for the inconvenience.

**Pull request merged**
