### PR TITLE
Linked the Hacktober fest header logo to home

### PR DESCRIPTION
**Pull request by Haniket**
issue #1 
I resolved the issue by linking the hacktober fest header logo to home and making it pointer

### CODE REVIEW

**Review by Castella1313 — APPROVED** [review]

**Comment by Castella1313** [comment]
resolve the conflicts

**Comment by Haniket** [comment]
> resolve the conflicts



> resolve the conflicts

@Castella1313 why is it coming and how to solve it..........plz help

**Comment by Haniket** [comment]
> resolve the conflicts

@Castella1313 conflicts resolved........

**Comment by Castella1313** [comment]
@Haniket Yep!! Everything is perfect now, just waiting for @Hardikag17 to approve the pull request :))

**Comment by Haniket** [comment]
@Castella1313 @Hardikag17  plz help me merging my PR plz review my PR

**Comment by Castella1313** [comment]
@Haniket resolve the conflicts

**Comment by Castella1313** [comment]
Nice :))))

**Comment by Haniket** [comment]
conflict resolved.......

**Review by Castella1313 — APPROVED** [review]

**Pull request merged**
