### PR TITLE
added countdown in the home page

### PR DESCRIPTION
**Pull request by flitzmare**
I added a countdown component in the home page based on the issue number #49

### CODE REVIEW

**Comment by Castella1313** [comment]
@flitzmare would you mind adding it just below the navbar with text color white :)

**Comment by flitzmare** [comment]
> @flitzmare would you mind adding it just below the navbar with text color white :)

sure, here you go 😄

**Comment by Castella1313** [comment]
resolve the conflicts

**Comment by Castella1313** [comment]
@flitzmare good job :)

**Review by Castella1313 — APPROVED** [review]

**Pull request merged**
