### PR TITLE
Add a link to About section from Explore button.

### PR DESCRIPTION
**Pull request by JoseRivera12**

### CODE REVIEW

**Review by Castella1313 — CHANGES_REQUESTED** [review]
This link isn't working

**Comment by JoseRivera12** [comment]
I tested in my pc and it's working

**Comment by JoseRivera12** [comment]
<a href="https://imgbb.com/">ezgif-com-gif-maker</a>

**Comment by JoseRivera12** [comment]
@Castella1313

**Comment by Castella1313** [comment]
@Hardikag17 is the link working in your system??

**Comment by ads-22** [comment]
@Castella1313 its working

**Review by Castella1313 — APPROVED** [review]

**Pull request merged**
