### PR TITLE
Spacing is fixed

### PR DESCRIPTION
**Pull request by tanujajoshi1**
Would be grateful if the PR gets accepted #22

### CODE REVIEW

**Comment by Castella1313** [comment]
@tanujajoshi1 can you please mention the issue number you have resolved in your pr!

**Comment by tanujajoshi1** [comment]
Issue no 22

**Comment by Castella1313** [comment]
#22 is the pr number, mention the issue number you have made the pr for!!

**Comment by tanujajoshi1** [comment]
Sorry, the issue number is #19

**Comment by Castella1313** [comment]
@tanujajoshi1 this issue isn't assigned to you, so closing your pr

**Pull request closed without merging**
