### PR TITLE
Fixed the comment syntax in css file and added z-index in nav bar 

### LINKED ISSUE #61: The comment in CSS code is wrong.
The comment in CSS code is wrong. you have used html comment syntax in css file instead of css syntax

I have made a pr to fix that (wasn't knowing there should be issue to make the pr so i"m making this issue. thank you. #46

### PR DESCRIPTION
**Pull request by Lilykhan786**
issue resolved #61 
there was  html comment tag in css file. 
cards were overflowing so i added z-index on navbar

### CODE REVIEW

**Comment by Castella1313** [comment]
@Lilykhan786 can you please mention the issue number you have resolved in the pr?

**Comment by Lilykhan786** [comment]
Wait there should be an issue number? oh sorry I didn't saw it I just fixed it by looking on the site :sweat:

**Comment by Castella1313** [comment]
> Wait there should be an issue number? oh sorry I didn't saw it I just fixed it by looking on the site 😓

@Lilykhan786 if the issue doesn't exist, you should create one and get it assigned to you, then you can mention the issue number.

**Comment by Lilykhan786** [comment]
oh ok thank you i'll try it and sorry for bothering u :sweat:

**Comment by Lilykhan786** [comment]
I have made the issue, what i have to do now :sweat:

**Comment by Castella1313** [comment]
@Lilykhan786 take it cool :)
I would suggest you reading the readme, it has each and everything mentioned :))))

**Comment by Castella1313** [comment]
resolve the conflicts by pulling the repository again and committing again as so many new branches has been merged

**Comment by Lilykhan786** [comment]
I think I messed up :disappointed: I deleted the forked repo and forked again I can't find that issue anymore, I guess I'll just work on UI improvement the I'll make new pr :sob:

**Pull request closed without merging**
