### PR TITLE
fixed issue Removed space between line issue #19

### PR DESCRIPTION
**Pull request by hansaj-sharma**
Added margin spacing using relative units, spacing works both on desktop and mobile screens #19 

Screenshot (69)

### CODE REVIEW

**Comment by hansaj-sharma** [comment]
Please review and approve

**Comment by Castella1313** [comment]
@hansaj-sharma can you please mention the issue number you have resolved in your pr!

**Comment by Castella1313** [comment]
@hansaj-sharma either mention the issue number in your pr's description or mention in the comment section of the issue

**Comment by hansaj-sharma** [comment]
@Castella1313  Sorry for the inconvenience, i will look into it, this is my first time contributing

**Comment by Castella1313** [comment]
@hansaj-sharma Ahh not a problem!! Keep learning :)
resolve the conflicts !!

**Comment by hansaj-sharma** [comment]
> @hansaj-sharma Ahh not a problem!! Keep learning :)
> resolve the conflicts !!

if possible can you tell how I should do it Help would be appreciated !

**Comment by Castella1313** [comment]
@hansaj-sharma resolve the conflicts by pulling the repository again and committing the changes again as so many new branches has been merged

**Pull request closed without merging**
