### PR TITLE
Feat add scroll

### PR DESCRIPTION
**Pull request by ShubhamSood1406**
#9 I added the functionality to Scroll Down To Numbers (Statistics) Section When Clicked On "Events" in Navbar.

### CODE REVIEW

**Comment by Castella1313** [comment]
@ShubhamSood1406 You must go through the instructions in the readme first. Although you aren't assigned this issue, since you have made this pr and even your work is amazing, we are considering your pr.

**Comment by Castella1313** [comment]
@ShubhamSood1406 would you mind adding scroll link in resources section in the navbar to the flash cards in the home page??

**Comment by ShubhamSood1406** [comment]
> @ShubhamSood1406 You must go through the instructions in the readme first. Although you aren't assigned this issue, since you have made this pr and even your work is amazing, we are considering your pr.

Sorry, I by mistake send PR to #7 instead of #9. Now I corrected it, can you assign #7 PR to me?

**Review by Castella1313 — APPROVED** [review]

**Comment by Castella1313** [comment]
good work :)

**Pull request merged**
